# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-21 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('add_toc', models.BooleanField(default=False, help_text='Include a list of child links', verbose_name='Add TOC')),
            ],
            options={
                'verbose_name': 'Doc Page',
                'verbose_name_plural': 'Doc Pages',
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
    ]
